### ISSUE TITLE
How do I validate in build-time using Vite?

### ISSUE THREAD

**Issue by yamcodes** [lostfictions/znv#17]
Hey, thanks for the great library.
I've set this up in my `./config.ts` file as so:

```ts
import { parseEnv, z } from "znv";
import type { Environment } from "types";

const envSchema = z.object({
    VITE_MY_URL: z.string().url(),
});

/**
 * Validated environment variables
 */
export const env = parseEnv(import.meta.env, envSchema.shape);

/**
 * This const comes from the extension in `.env.%MODE%` files
 */
export const environment = import.meta.env.MODE as Environment;

```

An error is thrown when `VITE_MY_URL` is not supplied during runtime (i.e., in the browser).
However, is there a way to throw an error when running `vite build`? Currently it passes although I'd expect it to fail.

I thought the solution to run `tsx ./config.ts && vite build`, but that is not working and throwing this error:

```
> mvns-home@0.4.0 validate /Users/yamcodes/code/my-repo
> tsx src/config.ts

file:///Users/yamcodes/code/my-repo/node_modules/.pnpm/znv@0.4.0_zod@3.23.8/node_modules/znv/dist/parse-env.js:32
        const envValue = env[key];
                            ^

TypeError: Cannot read properties of undefined (reading 'VITE_MY_URL')
    at parseEnv (/Users/yamcodes/code/my-repo/node_modules/.pnpm/znv@0.4.0_zod@3.23.8/node_modules/znv/src/parse-env.ts:116:25)
    at <anonymous> (/Users/yborodetsky/code/storemavens/mvns-core/services/mvns-home/src/config.ts:15:20)
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async loadESM (node:internal/process/esm_loader:28:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12)

Node.js v20.11.1
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by blasdfaa** [comment]
You can reuse the validation scheme in your vite plugin. For example, like this 
```
// env/schema.ts
export const envSchema = z.object({
    VITE_MY_URL: z.string().url(),
});


// vite/vite-env-validator.ts
import type { Plugin } from 'vite'
import process from 'node:process'
import { z } from 'zod'
import { envSchema } from '../env/schema'

export function envValidator(): Plugin {
  return {
    name: 'vite-env-validator',
    configResolved({ env }) {
      try {
        envSchema.parse(env)
        // eslint-disable-next-line no-console
        console.log('\n✅ Environment variables validated successfully\n')
      }
      catch (error) {
        if (error instanceof z.ZodError) {
          console.error('\nEnvironment Variables Validation Error:')
          error.errors.forEach((err) => {
            console.error(`❌ ${err.path.join('.')}: ${err.message}`)
          })
          process.exit(1)
        }
      }
    },
  }
}

// vite.config.ts
import { defineConfig } from 'vite'
import { envValidator } from './vite/vite-env-validator'

export default defineConfig({
  plugins: [
    envValidator(),
   	// ...
  ],
})

// src/config/env.ts

import { envSchema } from 'env/schema'
import { parseEnv } from 'znv'

export const env = parseEnv(import.meta.env, envSchema.shape)
```

**Comment by lostfictions** [comment]
Closing per @blasdfaa's answer.

`tsx ./config.ts && vite build` will not work because it's running one process and then another -- these are two unrelated Node processes.
